# -*- coding: utf-8 -*-
"""End_to_End_ML_Platform_for_Financial_Fraud_Risk_Scoring.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VFMhQrfy5qCt6agCG_JBWSGjzrxN61HF

## End-to-End ML Platform for Financial Fraud / Risk Scoring

# Import libraries
"""

import pandas as pd
import numpy as np
import os, kagglehub
import joblib

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
import xgboost as xgb
import lightgbm as lgb
from sklearn.metrics import roc_auc_score, accuracy_score, precision_score, recall_score
import mlflow
import mlflow.sklearn

import warnings
warnings.filterwarnings("ignore")

"""# Load dataset"""

path = kagglehub.dataset_download("mlg-ulb/creditcardfraud")
data = pd.read_csv(os.path.join(path, "creditcard.csv"))

data.head()

"""# Performing Exploratory Data Analysis(EDA) to understand structure and quality of data"""

data.info()

"""# Checking the value count of class that refers as 1 as fraud transaction and 0 as Legit transaction"""

data["Class"].value_counts()

"""This data is highly unbalanced,
seperating data to do analysis
"""

legit = data[data.Class == 0]
fraud = data[data.Class == 1]

print(legit.shape)
print(fraud.shape)

legit.Amount.describe()

fraud.Amount.describe()

fraud.head()

data.groupby("Class").mean()

"""As we can see there is huge difference between the mean of legit data and fraud data so doing unsampling by distributing dataset randomly into equal number for both the transaction"""

legit_sample = legit.sample(n=492)

"""Now Concatenate both the data into one dataset by using concat from pandas"""

new_data = pd.concat([legit_sample, fraud], axis=0) # axis = 0(row) and axis = 1(column)

new_data.head(5)

new_data["Class"].value_counts()

new_data.groupby('Class').mean()

"""Split the dataset into X and Y for classification"""

X = new_data.drop(columns="Class", axis=1)
Y = new_data["Class"]

X

Y

"""Using train-test split from SKlearn for train and test"""

X_train, X_test , y_train, y_test = train_test_split(X, Y, test_size=0.2)

"""# Model Training

Lets create a pipeline for three different model and compare them.
"""

Models = {
    "RandomForest": RandomForestClassifier(n_estimators= 200, random_state= 42),
    "XGBoost": xgb.XGBClassifier(eval_metric = ["logloss", "auc"] ,n_estimators= 200, random_state= 42),
    "LightGBM": lgb.LGBMClassifier(n_estimators= 200, random_state= 42, verbosity = -1)
}

Results = {}

for name, model in Models.items():
  # train model
    model.fit(X_train, y_train)

    # Get predicted probabilities
    y_train_prob = model.predict_proba(X_train)[:, 1]
    y_test_prob = model.predict_proba(X_test)[:, 1]

    # Convert probabilities to binary predictions
    y_train_pred = (y_train_prob >= 0.5).astype(int)
    y_test_pred = (y_test_prob >= 0.5).astype(int)

    # Metrics
    roc_train = float(roc_auc_score(y_train, y_train_prob))
    roc_test = float(roc_auc_score(y_test, y_test_prob))
    precision = float(precision_score(y_test, y_test_pred))
    recall = float(recall_score(y_test, y_test_pred))
    accuracy = float(accuracy_score(y_test, y_test_pred))

  # check overfit/ underfit
    if roc_train - roc_test > 0.1:
        fit_status = "Overfit"
    elif roc_train < 0.6 and roc_test < 0.6:
        fit_status = "Underfit"
    else:
        fit_status = "Good fit"

    Results[name] = {
        "model": model,
         "metrics": {
            "roc_train": roc_train,
            "roc_test": roc_test,
            "precision": precision,
            "recall": recall,
            "accuracy": accuracy
        },
        "fit_status": fit_status
    }

Result_df = pd.DataFrame({
    model_name: {**metrics_info['metrics'], 'fit_status': metrics_info['fit_status']}
    for model_name, metrics_info in Results.items()
}).T

# Ensure numeric columns are float
numeric_cols = ['roc_train', 'roc_test', 'precision', 'recall', 'accuracy']
Result_df[numeric_cols] = Result_df[numeric_cols].apply(pd.to_numeric, errors='coerce')

# Show comparison table
print("\n== Model Comparison ==")
print(Result_df)

best_model = Result_df['roc_test'].idxmax()
best_model_score = Result_df.loc[best_model, 'roc_test']

print(f"\nBest Model: {best_model} with ROC Test Score: {best_model_score:.4f}")

best_model_save = Models[best_model]
print(best_model_save)

"""# Save the model using joblib"""

file_path = f"C:/Users/Ronak/OneDrive/Desktop/Credit/{best_model}.joblib"
joblib.dump(best_model_save, file_path)

print(f"Model saved as: {file_path}")

#best_model_save = Models[best_model]
#joblib.dump(best_model, 'C:/Users/Ronak/OneDrive/Desktop/Credit/Fraud_scoring.pkl')

"""## Performing MLflow Experiment"""

Results

print(type(Results))
print(Results)

# dagshub setup

import dagshub
dagshub.init(repo_owner='ronak3618', repo_name='MLflow_daghub_demo', mlflow=True)

mlflow.end_run()

# os.environ['MLFLOW_TRACKING_USERNAME'] = 'ronak3618'
# os.environ['MLFLOW_TRACKING_PASSWORD'] = '6e89bf0a7ef54d9e6605276a0519635d2352c412'
# os.environ['MLFLOW_TRACKING_URI'] = 'https://dagshub.com/ronak3618/MLflow_daghub_demo.mlflow'     !USE ALL THIS IF THE CODE SHOWS AN ERROR!

# mlflow.set_tracking_uri(uri = "http://127.0.0.1:5000/") Commented as i am not running it on dagshub server
mlflow.set_experiment("Creditcardfraud_Models")

for model_name, data in Results.items():

    with mlflow.start_run(run_name=model_name):

        # Log model
        mlflow.sklearn.log_model(
            sk_model=data["model"],
            artifact_path="model"
        )

        # Log metrics
        for metric_name, metric_value in data["metrics"].items():
            mlflow.log_metric(metric_name, metric_value)

        # Log tags
        mlflow.set_tag("fit_status", data["fit_status"])
        mlflow.set_tag("model_name", model_name)
print("DONE")

print(mlflow.get_tracking_uri())

"""## Register the model in MLflow"""

model_name = 'XGBoost'
run_id = input("Enter Run ID")
model_uri = f"runs:/{run_id}/model"

final = mlflow.register_model(
    model_uri,
    model_name)

"""## Load the model"""

model_name = 'LightGBM'
model_version = 1
model_uri = f"models:/{model_name}@challenger"  # models:/<YOUR_MODEL_NAME>/<YOUR_MODEL_VERSION>

loaded_model = mlflow.sklearn.load_model(model_uri)
y_pred = loaded_model.predict(X_test)
y_pred[:4]

dev_model_uri = f"models:/{model_name}@challenger"
prod_model = "credit-card-fraud-prod"

client = mlflow.MlflowClient()
client.copy_model_version(src_model_uri = dev_model_uri , dst_name = prod_model)



model_uri = f"models:/{prod_model}@champion"  # models:/<YOUR_MODEL_NAME>/<YOUR_MODEL_VERSION>

loaded_model = mlflow.sklearn.load_model(model_uri)
y_pred = loaded_model.predict(X_test)
y_pred[:4]

